[theme]
primaryColor = "#000000"              # Black (buttons, accents)
backgroundColor = "#FFD700"           # Bold Yellow (main background)
secondaryBackgroundColor = "#FFFACD"  # Light Yellow (sidebar and widgets)
textColor = "#000000"                 # Black text for contrast
font = "sans serif"
